### PR TITLE
Added Identities Templates

### PR DESCRIPTION
**Pull request by KetanChawda-MSFT**

### CODE REVIEW

**Comment by miaojiang** [comment]
@KetanChawda-MSFT thanks for the contribution. Not sure I see the difference between identities.aad.template.json and identities.template.json.

**Comment by KetanChawda-MSFT** [comment]
@miaojiang The difference is in properties as AAD type identity require `allowedTenants` property but others like Facebook and Microsoft etc doesn't require.

**Comment by miaojiang** [comment]
Got it, thanks. Merged.

**Comment by KetanChawda-MSFT** [comment]
@miaojiang Thanks.

**Pull request merged**
